import "server-only";
import { requireCurrentProfile } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";
import { roles, type AppRole } from "@/lib/constants/roles";
import type { z } from "zod";
import type { announcementSchema } from "@/lib/announcements/schemas";
import type { Announcement, AnnouncementSetup } from "@/lib/announcements/types";
import { notifyAnnouncementPublished } from "@/lib/announcements/email";
type Input = z.infer<typeof announcementSchema>;
export class AnnouncementError extends Error {}
const fail = (error: { message: string; code?: string } | null) => { if (error) throw new AnnouncementError(error.message || "Announcement could not be saved."); };
const map = (row: Record<string, unknown>): Announcement => { const roles = row.announcement_role_audiences as { role: string }[] | undefined; const classes = row.announcement_class_audiences as { class_id: string }[] | undefined; const sections = row.announcement_section_audiences as { section_id: string }[] | undefined; const years = row.announcement_academic_year_audiences as { academic_year_id: string }[] | undefined; const target = row.audience_scope === "all" ? "all" : roles?.length ? "role" : classes?.length ? "class" : sections?.length ? "section" : "academicYear"; const targetIds = target === "role" ? (roles ?? []).map((value) => value.role) : target === "class" ? (classes ?? []).map((value) => value.class_id) : target === "section" ? (sections ?? []).map((value) => value.section_id) : target === "academicYear" ? (years ?? []).map((value) => value.academic_year_id) : []; return { id: String(row.id), title: String(row.title), body: String(row.body), status: row.status as Announcement["status"], audienceLabel: target === "all" ? "All users" : `Targeted ${target}`, target, targetIds, publishedOn: row.published_at ? String(row.published_at).slice(0, 10) : null, expiresOn: row.expires_at ? String(row.expires_at).slice(0, 10) : null, createdAt: String(row.created_at), updatedAt: String(row.updated_at), authorId: String(row.author_id) }; };
export async function getVisibleAnnouncements(limit = 6) { await requireCurrentProfile(); const supabase = await createClient(); const { data, error } = await supabase.from("announcements").select("id,title,body,status,audience_scope,published_at,expires_at,created_at,updated_at,author_id").eq("status", "published").order("published_at", { ascending: false }).limit(limit); fail(error); return (data ?? []).map((row) => map(row as Record<string, unknown>)); }
export async function getAnnouncementSetup(): Promise<AnnouncementSetup> { const profile = await requireCurrentProfile(); if (profile.role !== "admin" && profile.role !== "teacher") throw new AnnouncementError("You cannot manage announcements."); const supabase = await createClient(); const [items, classes, sections, years, teacher] = await Promise.all([supabase.from("announcements").select("id,title,body,status,audience_scope,published_at,expires_at,created_at,updated_at,author_id,announcement_role_audiences(role),announcement_class_audiences(class_id),announcement_section_audiences(section_id),announcement_academic_year_audiences(academic_year_id)").eq("author_id", profile.id).order("updated_at", { ascending: false }), supabase.from("classes").select("id,name").order("display_order"), supabase.from("sections").select("id,name,classes!inner(name)").order("name"), supabase.from("academic_years").select("id,name").order("starts_on", { ascending: false }), profile.role === "teacher" ? supabase.from("teacher_assignments").select("section_id,sections!inner(id,name,classes!inner(name))") : Promise.resolve({ data: [], error: null })]); [items.error, classes.error, sections.error, years.error, teacher.error].forEach(fail); const sectionOptions = (sections.data ?? []).map((row) => ({ id: row.id, label: `${(row.classes as unknown as { name: string }).name} · ${row.name}` })); const teacherSections = [...new Map((teacher.data ?? []).map((row) => { const section = row.sections as unknown as { id: string; name: string; classes: { name: string } }; return [section.id, { id: section.id, label: `${section.classes.name} · ${section.name}` }] as const; })).values()]; return { announcements: (items.data ?? []).map((row) => map(row as Record<string, unknown>)), roles: [...roles], classes: classes.data ?? [], sections: sectionOptions, academicYears: (years.data ?? []).map((year) => ({ ...year, label: year.name })), teacherSections, isAdmin: profile.role === "admin" }; }
export async function saveAnnouncement(id: string | null, values: Input) { const profile = await requireCurrentProfile(); if (profile.role !== "admin" && profile.role !== "teacher") throw new AnnouncementError("You cannot manage announcements."); const roleIds = values.target === "role" ? values.targetIds as AppRole[] : []; const classIds = values.target === "class" ? values.targetIds : []; const sectionIds = values.target === "section" ? values.targetIds : []; const yearIds = values.target === "academicYear" ? values.targetIds : []; const supabase = await createClient(); const { error } = await supabase.rpc("save_announcement", { requested_announcement_id: id, requested_title: values.title, requested_body: values.body, requested_status: values.status, requested_audience_scope: values.target === "all" ? "all" : "targeted", requested_published_on: values.publishedOn || null, requested_expires_on: values.expiresOn || null, requested_roles: roleIds, requested_class_ids: classIds, requested_section_ids: sectionIds, requested_year_ids: yearIds }); fail(error); if (values.status === "published") await notifyAnnouncementPublished(); }
