import Link from "next/link";
import { CalendarCheck, Clock3, Users } from "lucide-react";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import type { ParentChildAttendance, PersonalAttendance } from "@/lib/attendance/types";

function Metrics({ items }: { items: { label: string; value: string | number }[] }) { return <section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3">{items.map((item) => <div key={item.label} className="bg-card p-5"><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-3 text-2xl font-semibold">{item.value}</p></div>)}</section>; }
export function TeacherDashboardView({ sections, tasks }: { sections: number; tasks: { section: { id: string; className: string; name: string }; total: number; marked: number }[] }) { return <div className="space-y-6"><Metrics items={[{ label: "Assigned sections", value: sections }, { label: "Today’s attendance tasks", value: tasks.length }, { label: "Timetable", value: "Not set up" }]} /><section className="rounded-lg border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Today’s attendance</h2><p className="mt-1 text-sm text-muted-foreground">Save progress section by section.</p></div><Button asChild><Link href="/teacher/attendance"><CalendarCheck className="size-4" />Mark attendance</Link></Button></div><ul className="mt-4 divide-y">{tasks.map((task) => <li key={task.section.id} className="flex items-center justify-between py-3 text-sm"><span>{task.section.className} · {task.section.name}</span><span className="text-muted-foreground">{task.marked}/{task.total} saved</span></li>)}</ul></section></div>; }
export function StudentDashboardView({ attendance }: { attendance: PersonalAttendance }) { return <div className="space-y-6"><Metrics items={[{ label: "Current class", value: attendance.section ?? "Not enrolled" }, { label: "Attendance rate", value: `${attendance.summary.rate}%` }, { label: "Recent records", value: attendance.recent.length }]} /><section className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Coming next</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Results and timetables are not available yet. Your current attendance is available now.</p><Button className="mt-4" variant="outline" asChild><Link href="/student/attendance">View attendance</Link></Button></section></div>; }
export function ParentDashboardView({ linkedChildren }: { linkedChildren: ParentChildAttendance[] }) { return <div className="space-y-6"><Metrics items={[{ label: "Linked children", value: linkedChildren.length }, { label: "Attendance available", value: linkedChildren.filter((child) => child.summary.total > 0).length }, { label: "Portal access", value: "Read-only" }]} /><section className="rounded-lg border bg-card p-5"><div className="flex items-center gap-2"><Users className="size-4 text-muted-foreground" /><h2 className="font-semibold">Children</h2></div><ul className="mt-4 divide-y">{linkedChildren.map((child) => <li key={child.studentId} className="flex items-center justify-between py-3"><div><p className="font-medium">{child.studentName}</p><p className="text-sm text-muted-foreground">{child.section ?? "No current section"}</p></div><StatusBadge label={`${child.summary.rate}% attendance`} status="info" /></li>)}</ul>{!linkedChildren.length ? <p className="mt-3 text-sm text-muted-foreground">No children are linked to this account yet.</p> : null}<Button className="mt-4" variant="outline" asChild><Link href="/parent/attendance"><Clock3 className="size-4" />View attendance</Link></Button></section></div>; }
