import Link from "next/link";
import { Bell, BookOpenCheck, CalendarCheck, CreditCard, LayoutGrid, UserRound } from "lucide-react";
import { AnnouncementList } from "@/components/announcements/announcement-list";
import { Button } from "@/components/ui/button";
import type { Announcement } from "@/lib/announcements/types";
const studentLinks = [{ href: "/student/timetable", label: "Timetable", icon: LayoutGrid }, { href: "/student/attendance", label: "Attendance", icon: CalendarCheck }, { href: "/student/results", label: "Results and report cards", icon: BookOpenCheck }, { href: "/student/announcements", label: "Announcements", icon: Bell }, { href: "#fees", label: "Fee records", icon: CreditCard }];
const parentLinks = [{ href: "/parent/timetable", label: "Timetables", icon: LayoutGrid }, { href: "/parent/attendance", label: "Attendance", icon: CalendarCheck }, { href: "/parent/results", label: "Results and report cards", icon: BookOpenCheck }, { href: "/parent/announcements", label: "Announcements", icon: Bell }, { href: "#fees", label: "Fee records", icon: CreditCard }];
function Links({ items }: { items: typeof studentLinks }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => { const Icon = item.icon; return <Link key={item.label} href={item.href} className="flex items-center gap-3 rounded-lg border bg-card p-4 text-sm font-medium hover:bg-muted"><Icon className="size-4 text-muted-foreground" />{item.label}</Link>; })}</div>; }
export function StudentPortalDashboard({ section, rate, announcements }: { section: string | null; rate: number; announcements: Announcement[] }) { return <div className="space-y-6"><section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3"><div className="bg-card p-5"><UserRound className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Class and section</p><p className="mt-1 font-semibold">{section ?? "Not enrolled"}</p></div><div className="bg-card p-5"><CalendarCheck className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Attendance rate</p><p className="mt-1 text-2xl font-semibold">{rate}%</p></div><div className="bg-card p-5"><CreditCard className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Fee records</p><p className="mt-1 font-semibold">Coming soon</p></div></section><Links items={studentLinks} /><section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent announcements</h2><Button asChild size="sm" variant="outline"><Link href="/student/announcements">View all</Link></Button></div><AnnouncementList announcements={announcements} empty="No recent announcements." /></section></div>; }
export function ParentPortalDashboard({ childrenCount, announcements }: { childrenCount: number; announcements: Announcement[] }) { return <div className="space-y-6"><section className="grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3"><div className="bg-card p-5"><UserRound className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Linked children</p><p className="mt-1 text-2xl font-semibold">{childrenCount}</p></div><div className="bg-card p-5"><BookOpenCheck className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Academic access</p><p className="mt-1 font-semibold">Read-only</p></div><div id="fees" className="bg-card p-5"><CreditCard className="size-4 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Fee records</p><p className="mt-1 font-semibold">Coming soon</p></div></section><Links items={parentLinks} /><section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent announcements</h2><Button asChild size="sm" variant="outline"><Link href="/parent/announcements">View all</Link></Button></div><AnnouncementList announcements={announcements} empty="No recent announcements." /></section></div>; }
