import "server-only";
import { requireRole } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";
import { calculateFeeStatus } from "@/lib/fees/calculations";
import type { z } from "zod";
import type { feePaymentSchema, feeQuerySchema, feeRecordSchema, feeTypeSchema } from "@/lib/fees/schemas";

type Query = z.infer<typeof feeQuerySchema>;
type FeeTypeInput = z.infer<typeof feeTypeSchema>;
type FeeRecordInput = z.infer<typeof feeRecordSchema>;
type FeePaymentInput = z.infer<typeof feePaymentSchema>;
export type FeeRow = { id: string; studentId: string; studentName: string; admissionNumber: string; feeType: string; academicYear: string; term: string | null; amountDue: number; amountPaid: number; balance: number; dueDate: string; status: "unpaid" | "partially_paid" | "paid" | "overdue"; notes: string | null; payments: Array<{ id: string; amount: number; paidOn: string; paymentMethod: string; receiptNumber: string; notes: string | null }> };
const error = (value: { message: string; code?: string } | null) => { if (value) throw new Error(value.code === "23505" ? "A record with that reference already exists." : value.message); };
const fullName = (record: { first_name: string; last_name: string }) => `${record.first_name} ${record.last_name}`.trim();

export async function getFeeSetup() { await requireRole("admin"); const supabase = await createClient(); const [types, students, years, terms] = await Promise.all([supabase.from("fee_types").select("id, name, description, default_amount, frequency, is_active, academic_year_id").order("name"), supabase.from("students").select("id, first_name, last_name, admission_number").eq("status", "active").order("first_name"), supabase.from("academic_years").select("id, name, status").order("starts_on", { ascending: false }), supabase.from("terms").select("id, name, academic_year_id").order("starts_on", { ascending: false })]); [types.error, students.error, years.error, terms.error].forEach(error); return { types: (types.data ?? []).map((item) => ({ id: item.id, name: item.name, description: item.description, defaultAmount: Number(item.default_amount), frequency: item.frequency, isActive: item.is_active, academicYearId: item.academic_year_id })), students: (students.data ?? []).map((item) => ({ id: item.id, name: fullName(item), admissionNumber: item.admission_number })), years: years.data ?? [], terms: terms.data ?? [] }; }

function mapFee(row: Record<string, unknown>): FeeRow { const student = row.students as { id: string; first_name: string; last_name: string; admission_number: string }; const type = row.fee_types as { name: string }; const year = row.academic_years as { name: string }; const term = row.terms as { name: string } | null; const payments = ((row.fee_payments as Array<Record<string, unknown>> | null) ?? []).map((item) => ({ id: String(item.id), amount: Number(item.amount), paidOn: String(item.paid_on), paymentMethod: String(item.payment_method), receiptNumber: String(item.receipt_number), notes: item.notes ? String(item.notes) : null })); const amountDue = Number(row.amount_due); const amountPaid = payments.reduce((total, payment) => total + payment.amount, 0); const dueDate = String(row.due_date); return { id: String(row.id), studentId: student.id, studentName: fullName(student), admissionNumber: student.admission_number, feeType: type.name, academicYear: year.name, term: term?.name ?? null, amountDue, amountPaid, balance: Math.max(0, amountDue - amountPaid), dueDate, status: calculateFeeStatus(amountDue, amountPaid, dueDate), notes: row.notes ? String(row.notes) : null, payments }; }
export async function listAdminFees(query: Query) { await requireRole("admin"); const supabase = await createClient(); const start = (query.page - 1) * query.pageSize; let request = supabase.from("fee_records").select("id, student_id, amount_due, due_date, status, notes, students!inner(id, first_name, last_name, admission_number), fee_types!inner(name), academic_years!inner(name), terms!left(name), fee_payments(id, amount, paid_on, payment_method, receipt_number, notes)", { count: "exact" }).order("due_date", { ascending: false }); if (query.status) request = request.eq("status", query.status); if (query.studentId) request = request.eq("student_id", query.studentId); if (query.academicYearId) request = request.eq("academic_year_id", query.academicYearId); const { data, count, error: listError } = await request.range(start, start + query.pageSize - 1); error(listError); return { items: (data ?? []).map((item) => mapFee(item as unknown as Record<string, unknown>)), total: count ?? 0, page: query.page, pageSize: query.pageSize }; }
export async function saveFeeType(values: FeeTypeInput, id?: string) { await requireRole("admin"); const supabase = await createClient(); const row = { name: values.name, description: values.description || null, default_amount: values.defaultAmount, frequency: values.frequency, is_active: values.isActive, academic_year_id: values.academicYearId }; const result = id ? await supabase.from("fee_types").update(row).eq("id", id) : await supabase.from("fee_types").insert(row); error(result.error); }
export async function saveFeeRecord(values: FeeRecordInput, id?: string) { await requireRole("admin"); const supabase = await createClient(); const { error: saveError } = await supabase.rpc("save_fee_record", { requested_fee_record_id: id ?? null, requested_student_id: values.studentId, requested_fee_type_id: values.feeTypeId, requested_academic_year_id: values.academicYearId, requested_term_id: values.termId, requested_amount_due: values.amountDue, requested_due_date: values.dueDate, requested_notes: values.notes }); error(saveError); }
export async function recordFeePayment(values: FeePaymentInput) { await requireRole("admin"); const supabase = await createClient(); const { error: saveError } = await supabase.rpc("record_fee_payment", { requested_fee_record_id: values.feeRecordId, requested_amount: values.amount, requested_paid_on: values.paidOn, requested_payment_method: values.paymentMethod, requested_receipt_number: values.receiptNumber, requested_notes: values.notes }); error(saveError); }
async function listStudentFees(studentId: string) { const supabase = await createClient(); const { data, error: listError } = await supabase.from("fee_records").select("id, student_id, amount_due, due_date, status, notes, students!inner(id, first_name, last_name, admission_number), fee_types!inner(name), academic_years!inner(name), terms!left(name), fee_payments(id, amount, paid_on, payment_method, receipt_number, notes)").eq("student_id", studentId).order("due_date", { ascending: false }).limit(50); error(listError); return (data ?? []).map((item) => mapFee(item as unknown as Record<string, unknown>)); }
export async function getOwnFees() { const profile = await requireRole("student"); const supabase = await createClient(); const { data, error: studentError } = await supabase.from("students").select("id, first_name, last_name").eq("profile_id", profile.id).maybeSingle(); error(studentError); if (!data) throw new Error("No student record is linked to this account."); return { studentName: fullName(data), fees: await listStudentFees(data.id) }; }
export async function getParentFees() { const profile = await requireRole("parent"); const supabase = await createClient(); const { data: parent, error: parentError } = await supabase.from("parents").select("id").eq("profile_id", profile.id).maybeSingle(); error(parentError); if (!parent) return []; const { data: links, error: linkError } = await supabase.from("parent_student_links").select("student_id, students!inner(first_name, last_name)").eq("parent_id", parent.id); error(linkError); return Promise.all((links ?? []).map(async (link) => ({ studentId: link.student_id, studentName: fullName(link.students as unknown as { first_name: string; last_name: string }), fees: await listStudentFees(link.student_id) }))); }
